// Generated by Xata Codegen 0.18.0. Please do not edit.
import { buildClient } from '@xata.io/client'
/** @typedef { import('./types').SchemaTables } SchemaTables */
/** @type { SchemaTables } */
const tables = [
  {
    name: 'Products',
    columns: [
      { name: 'title', type: 'string' },
    ],
  },
  {
    name: 'Brands',
    columns: [
      { name: 'title', type: 'string' },
    ],
  },
]
/** @type { import('@xata.io/client').ClientConstructor<{}> } */
const DatabaseClient = buildClient()
const defaultOptions = {
  databaseURL:  "https://maria-studiodialect-s-workspace-j3k9ii.eu-west-1.xata.sh/db/heinemann",
}
/** @typedef { import('./types').DatabaseSchema } DatabaseSchema */
/** @extends DatabaseClient<DatabaseSchema> */
export class XataClient extends DatabaseClient {
  constructor(options) {
    super({ ...defaultOptions, ...options }, tables)
  }
}
let instance = undefined
/** @type { () => XataClient } */
export const getXataClient = () => {
  if (instance) return instance
  instance = new XataClient()
  return instance
}
